apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dgi8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0066-tenant/tkrw-pr712-0075-0066-app/devfile-sample-dgi8@sha256:7e85c5d19f2305fb7e195b702375593ea00148c8c357d58be91fe08bee5046ff
        name: my-nodejs
        resources: {}
status: {}
